from __future__ import annotations

from typing import Any

from atas_market_structure.models._enums import (
    AdapterTriggerType,
    DepthCoverageState,
    DerivedBias,
    EventType,
    GapDirection,
    GapFillLikelihood,
    GapFillState,
    KeyLevelRole,
    KeyLevelState,
    LargeLiquidityStatus,
    LiquidityLevelType,
    LiquidityMemoryClassification,
    MACRO_TIMEFRAMES,
    MeasurementReferenceKind,
    ObservationOriginMode,
    INTRADAY_TIMEFRAMES,
    OrderFlowSignalType,
    PostHarvestOutcome,
    ReplayAcquisitionMode,
    ReplayVerificationStatus,
    SessionCode,
    SETUP_TIMEFRAMES,
    EXECUTION_TIMEFRAMES,
    StructureSide,
    SwingKind,
    Timeframe,
)
from atas_market_structure.models._refs import (
    InstrumentRef,
    SourceRef,
)
from atas_market_structure.models._adapter_states import (
    AdapterDepthCoverage,
    AdapterEmaContext,
    AdapterEnvelopeBase,
    AdapterInitiativeDriveState,
    AdapterManipulationLegState,
    AdapterMeasuredMoveState,
    AdapterPostHarvestResponseState,
    AdapterPriceState,
    AdapterReferenceLevel,
    AdapterSamePriceReplenishmentState,
    AdapterSessionContext,
    AdapterSignificantLiquidityLevel,
    AdapterTradeSummary,
    AdapterZoneInteraction,
    AdapterGapReferenceState,
)
from atas_market_structure.models._observed import (
    DecisionLayerSet,
    DepthSnapshotPayload,
    EventSnapshotPayload,
    ObservedContextWindow,
    ObservedCrossSessionSequence,
    ObservedEventMarker,
    ObservedExertionZone,
    ObservedGapReference,
    ObservedInitiativeDrive,
    ObservedLiquidityEpisode,
    ObservedLiquidityLevel,
    ObservedManipulationLeg,
    ObservedMeasuredMove,
    ObservedOrderFlowSignal,
    ObservedPostHarvestResponse,
    ObservedProcessContext,
    ObservedRange,
    ObservedSecondFeature,
    ObservedSessionStats,
    ObservedSessionWindow,
    ObservedSwingPoint,
    ObservedValueArea,
    ObservedLargeLiquidityLevel,
)
from atas_market_structure.models._derived import (
    DerivedGapAssessment,
    DerivedKeyLevelAssessment,
    DerivedLiquidityMemoryInterpretation,
    DerivedProcessInterpretation,
    DerivedStructureAnalysis,
    DerivedWindowInterpretation,
    KnowledgeRoute,
)
from atas_market_structure.models._adapter_payloads import (
    AdapterBookmark,
    AdapterBurstWindow,
    AdapterContinuousStatePayload,
    AdapterDepthEvent,
    AdapterHistoryBar,
    AdapterHistoryBarsPayload,
    AdapterHistoryFootprintBar,
    AdapterHistoryFootprintLevel,
    AdapterHistoryFootprintPayload,
    AdapterSecondFeature,
    AdapterTradeEvent,
    AdapterTriggerBurstPayload,
    AdapterTriggerInfo,
)
from atas_market_structure.models._replay import (
    ReplayAiBriefing,
    ReplayAiChatAttachment,
    ReplayAiChatContent,
    ReplayAiChatMessage,
    ReplayAiChatPreset,
    ReplayAiChatRequest,
    ReplayAiChatResponse,
    ReplayAiEntryReview,
    ReplayAiInvalidationReview,
    ReplayAiReviewContent,
    ReplayAiReviewRequest,
    ReplayAiReviewResponse,
    ReplayAiScriptReview,
    ReplayAiZoneReview,
    ReplayCachePolicy,
    ReplayChartBar,
    ReplayEventAnnotation,
    ReplayFocusRegion,
    ReplayFootprintBarDetail,
    ReplayFootprintLevelDetail,
    ReplayLiveStreamState,
    ReplayManualRegionAnnotationAcceptedResponse,
    ReplayManualRegionAnnotationEnvelope,
    ReplayManualRegionAnnotationRecord,
    ReplayManualRegionAnnotationRequest,
    ReplayOperatorEntryAcceptedResponse,
    ReplayOperatorEntryEnvelope,
    ReplayOperatorEntryListQuery,
    ReplayOperatorEntryRecord,
    ReplayOperatorEntryRequest,
    ReplayStrategyCandidate,
    ReplayVerificationState,
    ReplayWorkbenchAcceptedResponse,
    ReplayWorkbenchAcceptedSummary,
    ReplayWorkbenchAckRebuildResult,
    ReplayWorkbenchAckVerification,
    ReplayWorkbenchAtasBackfillAcceptedResponse,
    ReplayWorkbenchAtasBackfillRecord,
    ReplayWorkbenchAtasBackfillRequest,
    ReplayWorkbenchAtasBackfillStatus,
    ReplayWorkbenchBuildAction,
    ReplayWorkbenchBuildRequest,
    ReplayWorkbenchBuildResponse,
    ReplayWorkbenchCacheEnvelope,
    ReplayWorkbenchCacheRecord,
    ReplayWorkbenchGapSegment,
    ReplayWorkbenchIntegrity,
    ReplayWorkbenchInvalidationRequest,
    ReplayWorkbenchInvalidationResponse,
    ReplayWorkbenchLiveSourceStatus,
    ReplayWorkbenchLiveStatusResponse,
    ReplayWorkbenchLiveTailResponse,
    ReplayWorkbenchRebuildLatestRequest,
    ReplayWorkbenchRebuildLatestResponse,
    ReplayWorkbenchSnapshotPayload,
)
from atas_market_structure.models._chat import (
    ChatAnnotation,
    ChatHandoffPacket,
    ChatHandoffRequest,
    ChatHandoffResponse,
    ChatLifecycleEvaluateRequest,
    ChatLifecycleEvaluateResponse,
    ChatLifecycleTransition,
    ChatMessage,
    ChatMessagesEnvelope,
    ChatObjectsEnvelope,
    ChatPlanCard,
    ChatReplyRequest,
    ChatReplyResponse,
    ChatSession,
    ChatSessionEnvelope,
    ChatSessionsEnvelope,
    ChatWindowRange,
    CreateChatMessageRequest,
    CreateChatSessionRequest,
    BuildPromptBlocksRequest,
    PromptBlock,
    PromptBlocksEnvelope,
    SessionMemory,
    SessionMemoryEnvelope,
    UpdateChatSessionRequest,
    UpdateMountedMessageRequest,
)
from atas_market_structure.models._responses import (
    AdapterAcceptedSummary,
    AdapterAcceptedResponse,
    AdapterBackfillAcknowledgeRequest,
    AdapterBackfillAcknowledgeResponse,
    AdapterBackfillCommand,
    AdapterBackfillDispatchResponse,
    AdapterBridgedArtifact,
    AnalysisEnvelope,
    DepthSnapshotAcceptedResponse,
    IngestionAcceptedResponse,
    IngestionEnvelope,
    LiquidityMemoryEnvelope,
    LiquidityMemoryRecord,
    MarketStructurePayload,
    MachineStrategyEntryArchetype,
    MachineStrategyHints,
    MachineStrategyCard,
    MachineStrategyIndex,
    MachineStrategyIndexEntry,
    MachineStrategyMatchRequirements,
    MachineStrategySummary,
)
from pydantic import BaseModel


_MODEL_REBUILD_NAMESPACE = {**globals(), "Any": Any}
for _value in tuple(globals().values()):
    if not isinstance(_value, type):
        continue
    if not issubclass(_value, BaseModel):
        continue
    try:
        _value.model_rebuild(_types_namespace=_MODEL_REBUILD_NAMESPACE, raise_errors=False)
    except AttributeError:
        continue
