"use strict";

const fs = require("fs");
const path = require("path");
const { chromium } = require("playwright");

function parseArgs(argv) {
  const config = {
    url: process.env.REPLAY_WORKBENCH_URL || "http://127.0.0.1:8080/workbench/replay",
    headless: !["0", "false", "no"].includes(String(process.env.REPLAY_WORKBENCH_HEADLESS || "1").trim().toLowerCase()),
    timeoutMs: Number(process.env.REPLAY_WORKBENCH_TIMEOUT_MS || "180000"),
    outputDir: path.resolve(
      process.cwd(),
      process.env.REPLAY_WORKBENCH_REPORT_DIR || path.join("artifacts", "replay-workbench-button-regression"),
    ),
  };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--url" && argv[index + 1]) {
      config.url = argv[index + 1];
      index += 1;
      continue;
    }
    if (arg === "--headed") {
      config.headless = false;
      continue;
    }
    if (arg === "--headless") {
      config.headless = true;
      continue;
    }
    if (arg === "--timeout-ms" && argv[index + 1]) {
      config.timeoutMs = Number(argv[index + 1]) || config.timeoutMs;
      index += 1;
      continue;
    }
    if (arg === "--output-dir" && argv[index + 1]) {
      config.outputDir = path.resolve(process.cwd(), argv[index + 1]);
      index += 1;
    }
  }
  return config;
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function ensureDirectory(targetPath) {
  fs.mkdirSync(targetPath, { recursive: true });
}

function writeFixtureFiles(baseDir) {
  ensureDirectory(baseDir);
  const textPath = path.join(baseDir, "regression-note.md");
  const imagePath = path.join(baseDir, "regression-pixel.png");
  fs.writeFileSync(
    textPath,
    [
      "# Replay Workbench Regression",
      "",
      "This attachment is generated by the replay workbench regression runner.",
      `Generated at ${new Date().toISOString()}`,
      "",
      "- Purpose: exercise attachment buttons",
    ].join("\n"),
    "utf8",
  );
  fs.writeFileSync(
    imagePath,
    Buffer.from(
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a0cAAAAASUVORK5CYII=",
      "base64",
    ),
  );
  return { textPath, imagePath };
}

async function getElementState(page, selector) {
  return page.evaluate((query) => {
    const element = document.querySelector(query);
    if (!element) {
      return { exists: false, visible: false, disabled: false, text: "" };
    }
    const style = window.getComputedStyle(element);
    const rect = element.getBoundingClientRect();
    const hiddenByTree = element.hidden || element.getAttribute("aria-hidden") === "true";
    const visible = !hiddenByTree
      && style.display !== "none"
      && style.visibility !== "hidden"
      && style.opacity !== "0"
      && rect.width > 0
      && rect.height > 0;
    const disabled = !!element.disabled;
    const text = String(element.textContent || "").trim().replace(/\s+/g, " ");
    return { exists: true, visible, disabled, text };
  }, selector);
}

async function waitUntilEnabled(page, selector, timeoutMs) {
  await page.waitForFunction((query) => {
    const element = document.querySelector(query);
    if (!element) {
      return false;
    }
    const style = window.getComputedStyle(element);
    const rect = element.getBoundingClientRect();
    return !element.disabled
      && !element.hidden
      && style.display !== "none"
      && style.visibility !== "hidden"
      && rect.width > 0
      && rect.height > 0;
  }, selector, { timeout: timeoutMs });
}

async function waitUntilVisible(page, selector, timeoutMs) {
  await page.waitForFunction((query) => {
    const element = document.querySelector(query);
    if (!element) {
      return false;
    }
    const style = window.getComputedStyle(element);
    const rect = element.getBoundingClientRect();
    return !element.hidden
      && style.display !== "none"
      && style.visibility !== "hidden"
      && rect.width > 0
      && rect.height > 0;
  }, selector, { timeout: timeoutMs });
}

async function visibleSelectors(page, selector, keyBuilder) {
  return page.evaluate(({ query }) => {
    return Array.from(document.querySelectorAll(query))
      .map((node, index) => {
        const style = window.getComputedStyle(node);
        const rect = node.getBoundingClientRect();
        const visible = !node.hidden
          && style.display !== "none"
          && style.visibility !== "hidden"
          && rect.width > 0
          && rect.height > 0;
        if (!visible) {
          return null;
        }
        const attrs = Object.fromEntries(Array.from(node.attributes).map((attr) => [attr.name, attr.value]));
        return {
          index,
          text: String(node.textContent || "").trim().replace(/\s+/g, " "),
          attrs,
        };
      })
      .filter(Boolean);
  }, { query: selector }).then((items) => items.map((item) => ({
    selector: `${selector} >> nth=${item.index}`,
    key: keyBuilder(item),
    text: item.text,
    attrs: item.attrs,
  })));
}

function createReport(config) {
  return {
    startedAt: new Date().toISOString(),
    url: config.url,
    headless: config.headless,
    timeoutMs: config.timeoutMs,
    steps: [],
    buttons: {},
    pageErrors: [],
    consoleErrors: [],
    network4xx: [],
    network5xx: [],
    requestFailures: [],
    notes: [],
    artifacts: {},
  };
}

function ensureButton(report, key, meta = {}) {
  if (!report.buttons[key]) {
    report.buttons[key] = {
      key,
      selector: meta.selector || "",
      label: meta.label || key,
      source: meta.source || "script",
      attempts: [],
    };
    return report.buttons[key];
  }
  if (meta.selector && !report.buttons[key].selector) {
    report.buttons[key].selector = meta.selector;
  }
  if (meta.label && !report.buttons[key].label) {
    report.buttons[key].label = meta.label;
  }
  if (meta.source && report.buttons[key].source === "script") {
    report.buttons[key].source = meta.source;
  }
  return report.buttons[key];
}

function recordButtonAttempt(report, key, status, detail, meta = {}) {
  const entry = ensureButton(report, key, meta);
  entry.attempts.push({
    status,
    detail,
    at: new Date().toISOString(),
  });
}

function stepSummary(status, detail = "", extra = {}) {
  return {
    status,
    detail,
    ...extra,
  };
}

async function main() {
  const config = parseArgs(process.argv.slice(2));
  ensureDirectory(config.outputDir);
  const runId = timestamp();
  const runDir = path.join(config.outputDir, runId);
  ensureDirectory(runDir);
  const fixtureDir = path.join(runDir, "fixtures");
  const fixtures = writeFixtureFiles(fixtureDir);
  const report = createReport(config);
  report.artifacts.runDir = runDir;
  report.artifacts.fixtureText = fixtures.textPath;
  report.artifacts.fixtureImage = fixtures.imagePath;

  const browser = await chromium.launch({
    headless: config.headless,
  });
  const context = await browser.newContext({
    viewport: { width: 1680, height: 1180 },
  });
  await context.grantPermissions(["clipboard-read", "clipboard-write"], { origin: new URL(config.url).origin });
  const page = await context.newPage();
  page.setDefaultTimeout(config.timeoutMs);

  await page.addInitScript(() => {
    class MockRecognition {
      constructor() {
        this.lang = "zh-CN";
        this.interimResults = false;
        this.maxAlternatives = 1;
      }

      start() {
        setTimeout(() => {
          this.onstart?.();
        }, 20);
        setTimeout(() => {
          const event = {
            results: [
              [
                {
                  transcript: "语音回归测试",
                  confidence: 0.99,
                },
              ],
            ],
          };
          this.onresult?.(event);
        }, 80);
        setTimeout(() => {
          this.onend?.();
        }, 140);
      }

      stop() {
        setTimeout(() => {
          this.onend?.();
        }, 20);
      }

      abort() {
        setTimeout(() => {
          this.onend?.();
        }, 20);
      }
    }

    window.SpeechRecognition = window.SpeechRecognition || MockRecognition;
    window.webkitSpeechRecognition = window.webkitSpeechRecognition || MockRecognition;
    window.navigator.clipboard = window.navigator.clipboard || {
      async writeText() {},
      async readText() { return ""; },
    };
  });

  const pendingDialogHandlers = [];
  let allowArchiveDialog = false;

  page.on("dialog", async (dialog) => {
    const nextHandler = pendingDialogHandlers.shift();
    if (nextHandler) {
      await nextHandler(dialog);
      return;
    }
    if (dialog.type() === "prompt") {
      await dialog.accept(`REGTEST-${Date.now()}`);
      return;
    }
    if (dialog.type() === "confirm" && allowArchiveDialog) {
      await dialog.accept();
      allowArchiveDialog = false;
      return;
    }
    await dialog.dismiss();
  });

  page.on("pageerror", (error) => {
    report.pageErrors.push({
      message: error.message,
      stack: error.stack || "",
      at: new Date().toISOString(),
    });
  });

  page.on("console", (message) => {
    if (message.type() === "error") {
      report.consoleErrors.push({
        text: message.text(),
        location: message.location(),
        at: new Date().toISOString(),
      });
    }
  });

  page.on("response", (response) => {
    const url = response.url();
    if (!url.includes("/api/")) {
      return;
    }
    const item = {
      url,
      method: response.request().method(),
      status: response.status(),
      at: new Date().toISOString(),
    };
    if (response.status() >= 500) {
      report.network5xx.push(item);
    } else if (response.status() >= 400) {
      report.network4xx.push(item);
    }
  });

  page.on("requestfailed", (request) => {
    report.requestFailures.push({
      url: request.url(),
      method: request.method(),
      failure: request.failure(),
      at: new Date().toISOString(),
    });
  });

  async function withStep(name, action) {
    const startedAt = Date.now();
    const step = { name, startedAt: new Date(startedAt).toISOString() };
    try {
      const result = await action();
      Object.assign(step, stepSummary("pass", result?.detail || "", result?.meta || {}));
    } catch (error) {
      Object.assign(step, stepSummary("fail", error.message || String(error), { stack: error.stack || "" }));
    } finally {
      step.completedAt = new Date().toISOString();
      step.durationMs = Date.now() - startedAt;
      report.steps.push(step);
    }
  }

  async function runDialog(handler, action) {
    let handled = false;
    pendingDialogHandlers.push(async (dialog) => {
      handled = true;
      await handler(dialog);
    });
    await action();
    await sleep(200);
    if (!handled && pendingDialogHandlers.length) {
      pendingDialogHandlers.pop();
    }
  }

  async function clickSelector(buttonKey, selector, {
    source = "static",
    label = buttonKey,
    timeoutMs = 15000,
    postWaitMs = 250,
    action = null,
  } = {}) {
    ensureButton(report, buttonKey, { selector, label, source });
    const state = await getElementState(page, selector);
    if (!state.exists) {
      recordButtonAttempt(report, buttonKey, "skipped", "元素不存在。", { selector, label, source });
      return false;
    }
    if (!state.visible) {
      recordButtonAttempt(report, buttonKey, "skipped", "按钮当前未显示。", { selector, label, source });
      return false;
    }
    if (state.disabled) {
      recordButtonAttempt(report, buttonKey, "skipped", "按钮当前禁用。", { selector, label, source });
      return false;
    }
    try {
      await waitUntilVisible(page, selector, timeoutMs);
      if (typeof action === "function") {
        await action();
      } else {
        await page.locator(selector).first().click();
      }
      if (postWaitMs > 0) {
        await sleep(postWaitMs);
      }
      recordButtonAttempt(report, buttonKey, "pass", "点击成功。", { selector, label, source });
      return true;
    } catch (error) {
      recordButtonAttempt(report, buttonKey, "fail", error.message || String(error), { selector, label, source });
      return false;
    }
  }

  async function setFilesByButton(buttonKey, selector, files, meta = {}) {
    await clickSelector(buttonKey, selector, {
      ...meta,
      action: async () => {
        const chooserPromise = page.waitForEvent("filechooser", { timeout: 10000 });
        await page.locator(selector).first().click();
        const chooser = await chooserPromise;
        await chooser.setFiles(files);
      },
      postWaitMs: 800,
    });
  }

  async function runStreamButton(buttonKey, selector, {
    label = buttonKey,
    source = "static",
    timeoutMs = config.timeoutMs,
    stopAfterMs = 900,
    beforeClick = null,
  } = {}) {
    ensureButton(report, buttonKey, { selector, label, source });
    const state = await getElementState(page, selector);
    if (!state.exists || !state.visible || state.disabled) {
      recordButtonAttempt(
        report,
        buttonKey,
        "skipped",
        !state.exists ? "元素不存在。" : (!state.visible ? "按钮当前未显示。" : "按钮当前禁用。"),
        { selector, label, source },
      );
      return false;
    }
    try {
      if (typeof beforeClick === "function") {
        await beforeClick();
      }
      const responsePromise = page.waitForResponse((response) => {
        return response.request().method() === "POST"
          && response.url().includes("/stream")
          && response.status() === 200;
      }, { timeout: timeoutMs });
      await page.locator(selector).first().click();
      await responsePromise;
      await sleep(stopAfterMs);
      const stopState = await getElementState(page, "#aiChatStopButton");
      if (stopState.exists && stopState.visible && !stopState.disabled) {
        await page.locator("#aiChatStopButton").click();
        recordButtonAttempt(report, "aiChatStopButton", "pass", "停止流式生成成功。", {
          selector: "#aiChatStopButton",
          label: "aiChatStopButton",
          source: "static",
        });
      }
      await waitUntilEnabled(page, selector, timeoutMs).catch(() => null);
      recordButtonAttempt(report, buttonKey, "pass", "流式请求已启动。", { selector, label, source });
      return true;
    } catch (error) {
      recordButtonAttempt(report, buttonKey, "fail", error.message || String(error), { selector, label, source });
      return false;
    }
  }

  async function runReplyButton(buttonKey, selector, {
    label = buttonKey,
    source = "static",
    timeoutMs = config.timeoutMs,
    beforeClick = null,
  } = {}) {
    ensureButton(report, buttonKey, { selector, label, source });
    const state = await getElementState(page, selector);
    if (!state.exists || !state.visible || state.disabled) {
      recordButtonAttempt(
        report,
        buttonKey,
        "skipped",
        !state.exists ? "元素不存在。" : (!state.visible ? "按钮当前未显示。" : "按钮当前禁用。"),
        { selector, label, source },
      );
      return false;
    }
    try {
      if (typeof beforeClick === "function") {
        await beforeClick();
      }
      const responsePromise = page.waitForResponse((response) => {
        return response.request().method() === "POST"
          && response.url().includes("/reply")
          && response.status() === 200;
      }, { timeout: timeoutMs });
      await page.locator(selector).first().click();
      await responsePromise;
      await waitUntilEnabled(page, selector, timeoutMs).catch(() => null);
      recordButtonAttempt(report, buttonKey, "pass", "同步回复请求已完成。", { selector, label, source });
      return true;
    } catch (error) {
      recordButtonAttempt(report, buttonKey, "fail", error.message || String(error), { selector, label, source });
      return false;
    }
  }

  async function openSessionMoreMenu() {
    await clickSelector("sessionMoreButton", "#sessionMoreButton");
    await waitUntilVisible(page, "#sessionMoreMenu", 20000);
  }

  async function drawChartDraftRegion() {
    await waitUntilVisible(page, "#chartContainer", config.timeoutMs);
    const box = await page.locator("#chartContainer").boundingBox();
    if (!box) {
      throw new Error("chartContainer 没有可用坐标。");
    }
    const startX = box.x + box.width * 0.32;
    const startY = box.y + box.height * 0.38;
    const endX = box.x + box.width * 0.57;
    const endY = box.y + box.height * 0.54;
    await page.mouse.move(startX, startY);
    await page.mouse.down();
    await page.mouse.move(endX, endY, { steps: 12 });
    await page.mouse.up();
    await sleep(450);
  }

  async function prepareChartSelection() {
    await waitUntilVisible(page, "#chartContainer", config.timeoutMs);
    const box = await page.locator("#chartContainer").boundingBox();
    if (!box) {
      return;
    }
    await page.mouse.move(box.x + box.width * 0.62, box.y + box.height * 0.44);
    await page.mouse.click(box.x + box.width * 0.62, box.y + box.height * 0.44);
    await sleep(250);
  }

  async function captureStaticButtons() {
    const items = await page.evaluate(() => {
      return Array.from(document.querySelectorAll("button[id]")).map((button) => ({
        id: button.id,
        text: String(button.textContent || "").trim().replace(/\s+/g, " "),
      }));
    });
    items.forEach((item) => {
      ensureButton(report, item.id, {
        selector: `#${item.id}`,
        label: item.text || item.id,
        source: "static",
      });
    });
  }

  async function clickDynamicButtons(selector, keyBuilder, options = {}) {
    const entries = await visibleSelectors(page, selector, keyBuilder);
    for (const entry of entries) {
      await clickSelector(entry.key, entry.selector, {
        source: options.source || "dynamic",
        label: entry.text || entry.key,
        timeoutMs: options.timeoutMs || 12000,
      });
    }
  }

  async function runMessageActionButtons() {
    const entries = await visibleSelectors(page, "button[data-message-action]", (item) => {
      return `data-message-action:${item.attrs["data-message-action"] || "unknown"}`;
    });
    for (const entry of entries) {
      const action = entry.attrs["data-message-action"] || "";
      if (action === "prompt-trace") {
        await clickSelector(entry.key, entry.selector, {
          source: "dynamic",
          label: entry.text || entry.key,
        });
        await waitUntilVisible(page, "#promptTraceModal", config.timeoutMs).catch(() => null);
        continue;
      }
      if (action === "regenerate") {
        await runStreamButton(entry.key, entry.selector, {
          source: "dynamic",
          label: entry.text || entry.key,
          stopAfterMs: 650,
        });
        continue;
      }
      await clickSelector(entry.key, entry.selector, {
        source: "dynamic",
        label: entry.text || entry.key,
        postWaitMs: 400,
      });
    }
  }
